### ISSUE TITLE
Login Fail - Didn't get latest observation time

### ISSUE THREAD

**Issue by TTegdap** [keithprickett/lacrosse_weather#2]
Hello,

Can you verify this is still working for you? 

I received this error message "Warning: Didn't get latest observation time." 

So I ran lacrosse.py manually...

Logging in...
Traceback (most recent call last):
  File "C:\myweather\lacrosse.py", line 144, in <module>
    token = lacrosse_login(email, password)
  File "C:\myweather\lacrosse.py", line 52, in lacrosse_login
    raise ConnectionError("Login Failed. Check credentials and try again")
ConnectionError: Login Failed. Check credentials and try again

I have verified the credential I am inputtin in the script work in the La Crosse View app.

Any guidance would be greatly appreciated.

**Comment by keithprickett** [comment]
I no longer have lacrosse devices, but I am able to log in successfully still with the current code.  I'd double check you have the correct credentials.  If you are running manually as you mentioned, you need to update the credentials near line 140.
